### ISSUE TITLE
if environment is not behind TLS builtin registry should be deployed as insecure

### ISSUE THREAD

**Issue by jorgemoralespou** [eduk8s/eduk8s-operator#21]
When there's no `INGRESS_SECRET` variable defined, the builtin registry that gets deployed for every session should be configured as insecure registry so that it will not present a self signed certificate, allowing to work in environments like minikube.

**Comment by GrahamDumpleton** [comment]
It was more complicated than that.

The session image registry was only being deployed as insecure, but the ingress router was manufacturing its own secure root anyway with a self signed certificate. The next issue was that the docker daemon used for docker support didn't know it was an insecure registry and so when doing docker push would try and talk to it as https. This would see the self signed certificate generated by the nginx server and fail.

Solution was to run dockerd with insecure registry option to say the session image registry used http only. This way the docker push would use http. Also had to generate into the workshop container a containers.conf file for tools like skopeo which said it was insecure as well.

Finally, in order to be able to deploy from the image registry, you have to configure the Kubernetes cluster to see it as an insecure registry. For minikube you could do this by deploying minikube in the first place with a subnet for insecure registries which matched the IP that minikube would use. For example ``--insecure-registry=192.168.0.0/16``. Then deployments would work. Not sure how would reconfigure arbitrary Kubernetes cluster to see registry as insecure.

**Comment by jorgemoralespou** [comment]
When using containerd on the host, the configuration for registries is described in [this](https://github.com/containerd/cri/blob/master/docs/registry.md) doc.

Changing containerd configuration and restarting the daemon shouldn't kill the running pods, so an option would be to have a daemonset reconfigure the host's containerd configuration and restart the daemon. This daemonset would need to be privileged.

The more we look into this, the more it sounds we should only support insecure environments for development purposes, where we user can run scripts manually on the host.

**Comment by GrahamDumpleton** [comment]
Closing this in favour of https://github.com/eduk8s/eduk8s-operator/issues/29
